// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhtpaatnywkyqcatzvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaHRwYWF0bnl3a3lxY2F0enZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTA0OTEsImV4cCI6MjA2NDc2NjQ5MX0.qOO04PJtrU_AwJedYgs-x4l3QHTeLRSdmDX6TcrUbT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);